<?php

/*
| ------------------------------------------------------------------------------
| Página de "Información General del sitio web"
| ------------------------------------------------------------------------------
| Código generado por ACF Pro.
| Ha sido adaptado para traducciones.
|
*/

if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5b75935c64e29',
        'title' => 'Información general',
        'fields' => array(
            array(
                'key' => 'field_5b7593c4ac9fe',
                'label' => __('Horario', 'incognitos'),
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5b759aeecfe40',
                'label' => __('Estado', 'incognitos'),
                'name' => 'infoHorarioEstado',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'abierto' => __('Abierto', 'incognitos'),
                    'cerrado' => __('Cerrado', 'incognitos'),
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'default_value' => 'abierto',
                'layout' => 'horizontal',
                'return_format' => 'value',
                'save_other_choice' => 0,
            ),
            array(
                'key' => 'field_5b7595e9fae15',
                'label' => __('Horario laboral', 'incognitos'),
                'name' => 'infoHorarioGeneral',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5b759aeecfe40',
                            'operator' => '==',
                            'value' => 'abierto',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => 'field_5b75964efae16',
                'min' => 0,
                'max' => 7,
                'layout' => 'block',
                'button_label' => __('Insertar día', 'incognitos'),
                'sub_fields' => array(
                    array(
                        'key' => 'field_5b75964efae16',
                        'label' => __('Día de la semana', 'incognitos'),
                        'name' => 'generalDia',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'lunes' => __('Lunes', 'incognitos'),
                            'martes' => __('Martes', 'incognitos'),
                            'miercoles' => __('Miércoles', 'incognitos'),
                            'jueves' => __('Jueves', 'incognitos'),
                            'viernes' => __('Viernes', 'incognitos'),
                            'sabado' => __('Sábado', 'incognitos'),
                            'domingo' => __('Domingo', 'incognitos'),
                        ),
                        'default_value' => array(
                            0 => 'lunes',
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5b7596f4fae17',
                        'label' => __('de', 'incognitos'),
                        'name' => 'generalDeHora',
                        'type' => 'time_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5b759e1520d08',
                                    'operator' => '!=',
                                    'value' => 'true',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '12',
                            'class' => '',
                            'id' => '',
                        ),
                        'display_format' => 'g:i a',
                        'return_format' => 'g:i a',
                    ),
                    array(
                        'key' => 'field_5b759735fae18',
                        'label' => __('a', 'incognitos'),
                        'name' => 'generalAHora',
                        'type' => 'time_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5b759e1520d08',
                                    'operator' => '!=',
                                    'value' => 'true',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '12',
                            'class' => '',
                            'id' => '',
                        ),
                        'display_format' => 'g:i a',
                        'return_format' => 'g:i a',
                    ),
                    array(
                        'key' => 'field_5bb7832e22a53',
                        'label' => __('y de', 'incognitos'),
                        'name' => 'generalDeHoraTarde',
                        'type' => 'time_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5b759e1520d08',
                                    'operator' => '!=',
                                    'value' => 'true',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '12',
                            'class' => '',
                            'id' => '',
                        ),
                        'display_format' => 'g:i a',
                        'return_format' => 'g:i a',
                    ),
                    array(
                        'key' => 'field_5bb7833a22a54',
                        'label' => __('a', 'incognitos'),
                        'name' => 'generalAHoraTarde',
                        'type' => 'time_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5b759e1520d08',
                                    'operator' => '!=',
                                    'value' => 'true',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '12',
                            'class' => '',
                            'id' => '',
                        ),
                        'display_format' => 'g:i a',
                        'return_format' => 'g:i a',
                    ),
                    array(
                        'key' => 'field_5b759e1520d08',
                        'label' => __('¿Cerrado?', 'incognitos'),
                        'name' => 'generalCerrado',
                        'type' => 'checkbox',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'true' => __('Sí', 'incognitos'),
                        ),
                        'allow_custom' => 0,
                        'default_value' => array(
                        ),
                        'layout' => 'horizontal',
                        'toggle' => 0,
                        'return_format' => 'value',
                        'save_custom' => 0,
                    ),
                    array(
                        'key' => 'field_5b76f23b22878',
                        'label' => 'Descripción',
                        'name' => 'generalCerradoDescripcion',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5b759e1520d08',
                                    'operator' => '==',
                                    'value' => 'true',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Cerrado',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5b759cccbe7bc',
                'label' => __('Cerrado por', 'incognitos'),
                'name' => 'infoHorarioCerrado',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5b759aeecfe40',
                            'operator' => '==',
                            'value' => 'cerrado',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5b759904a841f',
                        'label' => __('Título', 'incognitos'),
                        'name' => 'cerradoTitulo',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '40',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5b759904a8420',
                        'label' => __('de:', 'incognitos'),
                        'name' => 'cerradoDe',
                        'type' => 'date_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '30',
                            'class' => '',
                            'id' => '',
                        ),
                        'display_format' => 'd/m/Y',
                        'return_format' => 'd/m/Y',
                        'first_day' => 1,
                    ),
                    array(
                        'key' => 'field_5b759904a8421',
                        'label' => __('a:', 'incognitos'),
                        'name' => 'cerradoA',
                        'type' => 'date_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '30',
                            'class' => '',
                            'id' => '',
                        ),
                        'display_format' => 'd/m/Y',
                        'return_format' => 'd/m/Y',
                        'first_day' => 1,
                    ),
                ),
            ),
            array(
                'key' => 'field_5b759408ac9ff',
                'label' => __('Redes Sociales', 'incognitos'),
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5b75a51b571d0',
                'label' => '500px',
                'name' => '500px',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://',
            ),
            array(
                'key' => 'field_5b75a86bec1c0',
                'label' => 'Bitbucket',
                'name' => 'bitbucket',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://',
            ),
            array(
                'key' => 'field_5b75a5ed571d3',
                'label' => 'DeviantArt',
                'name' => 'deviantart',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://',
            ),
            array(
                'key' => 'field_5b75abed0fb79',
                'label' => 'Facebook',
                'name' => 'facebook',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://',
            ),
            array(
                'key' => 'field_5b75a4e246bf0',
                'label' => 'Flickr',
                'name' => 'flickr',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://',
            ),
            array(
                'key' => 'field_5b75a83cec1bf',
                'label' => 'GitHub',
                'name' => 'gitHub',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://',
            ),
            array(
                'key' => 'field_5b75a82cec1be',
                'label' => 'GitLab',
                'name' => 'gitLab',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://',
            ),
            array(
                'key' => 'field_5b75ac0e0fb7b',
                'label' => 'Google Plus',
                'name' => 'googlePlus',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://',
            ),
            array(
                'key' => 'field_5b75a503571cf',
                'label' => 'Instagram',
                'name' => 'instagram',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://',
            ),
            array(
                'key' => 'field_5b75a92aec1c1',
                'label' => 'Kickstarter',
                'name' => 'kickstarter',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://',
            ),
            array(
                'key' => 'field_5b75a6fb571d9',
                'label' => 'Linkedin',
                'name' => 'linkedin',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://',
            ),
            array(
                'key' => 'field_5b75a44c46bee',
                'label' => 'Meetup',
                'name' => 'meetup',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://',
            ),
            array(
                'key' => 'field_5b75a535571d1',
                'label' => 'Pinterest',
                'name' => 'pinterest',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://',
            ),
            array(
                'key' => 'field_5b75ac260fb7c',
                'label' => 'RSS',
                'name' => 'rss',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://',
            ),
            array(
                'key' => 'field_5b75a753571db',
                'label' => 'Sina Weibo',
                'name' => 'sinaWeibo',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://',
            ),
            array(
                'key' => 'field_5b75a695571d7',
                'label' => 'Snapchat',
                'name' => 'snapchat',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://',
            ),
            array(
                'key' => 'field_5b770481c3349',
                'label' => 'SoundCloud',
                'name' => 'soundcloud',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://',
            ),
            array(
                'key' => 'field_5b7700b1c3348',
                'label' => 'Spotify',
                'name' => 'spotify',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://',
            ),
            array(
                'key' => 'field_5b75ab1d8f68a',
                'label' => 'Steam',
                'name' => 'steam',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://',
            ),
            array(
                'key' => 'field_5b75a803ec1bd',
                'label' => 'TripAdvisor',
                'name' => 'tripAdvisor',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://',
            ),
            array(
                'key' => 'field_5b75a9d3ec1c3',
                'label' => 'Twitch',
                'name' => 'twitch',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://',
            ),
            array(
                'key' => 'field_5b75abfe0fb7a',
                'label' => 'Twitter',
                'name' => 'twitter',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://',
            ),
            array(
                'key' => 'field_5b75a6ce571d8',
                'label' => 'Viadeo',
                'name' => 'viadeo',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://',
            ),
            array(
                'key' => 'field_5b75a688571d6',
                'label' => 'Vimeo',
                'name' => 'vimeo',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://',
            ),
            array(
                'key' => 'field_5b75a9f3ec1c4',
                'label' => 'Vkontakte',
                'name' => 'vkontakte',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://',
            ),
            array(
                'key' => 'field_5b75a72e571da',
                'label' => 'Xing',
                'name' => 'xing',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://',
            ),
            array(
                'key' => 'field_5b75a678571d5',
                'label' => 'YouTube',
                'name' => 'youtube',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'https://',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'ws-general-info',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'seamless',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));
    
endif;