<?php

/*
| ------------------------------------------------------------------------------
| Página del "RGPD"
| ------------------------------------------------------------------------------
| Código generado por ACF Pro.
| Ha sido adaptado para traducciones.
|
*/

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5b3b1b84be484',
		'title' => __('Legal - RGPD', 'incognitos'),
		'fields' => array(
			array(
				'key' => 'field_5b3b21613f0e6',
				'label' => __('Responsable', 'incognitos'),
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5b3b2259511ec',
				'label' => __('Datos de contacto del Responsable', 'incognitos'),
				'name' => 'responsable',
				'type' => 'group',
				'instructions' => __('Persona/Empresa responsable del tratamiento de los datos.', 'incognitos'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'row',
				'sub_fields' => array(
					array(
						'key' => 'field_5b3b23811c117',
						'label' => __('Identidad', 'incognitos'),
						'name' => 'identidad',
						'type' => 'text',
						'instructions' => __('Nombre completo.', 'incognitos'),
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5b3b24111c118',
						'label' => __('ID', 'incognitos'),
						'name' => 'id',
						'type' => 'text',
						'instructions' => __('Identificador. Por ejemplo el NIF o el NIE o el CIF o etc.', 'incognitos'),
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5b3b24eaa1769',
						'label' => __('Dirección postal', 'incognitos'),
						'name' => 'direccion',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5b3b255aa176a',
						'label' => __('Teléfono', 'incognitos'),
						'name' => 'telefono',
						'type' => 'number',
						'instructions' => __('Utilice el <a target="_blank" rel="nofollow noopener noreferrer" href="https://es.wikipedia.org/wiki/Anexo:Prefijos_telef%C3%B3nicos_mundiales">prefijo telefónico</a> (+).', 'incognitos'),
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '+',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5b3b2587a176b',
						'label' => __('Correo electrónico', 'incognitos'),
						'name' => 'email',
						'type' => 'email',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
				),
			),
			array(
				'key' => 'field_5b3b2ca25b441',
				'label' => __('Datos de contacto del Representante', 'incognitos'),
				'name' => 'responsableRepresentante',
				'type' => 'group',
				'instructions' => __('Persona/Empresa responsable del tratamiento de los datos dentro de la Unión Europea; en el caso de que el <strong>Responsable</strong> resida fuera de ésta.', 'incognitos'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5b3b284a9162b',
						'label' => __('El responsable reside fuera de la Unión Europea?', 'incognitos'),
						'name' => 'representante',
						'type' => 'radio',
						'instructions' => __('Si la persona/empresa reside fuera de la Unión Europea es necesario un/na representante que resida en ésta.', 'incognitos'),
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'true' => __('Sí', 'incognitos'),
							'false' => __('No', 'incognitos'),
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'save_other_choice' => 0,
						'default_value' => 'false',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_5b3b280791626',
						'label' => __('Identidad', 'incognitos'),
						'name' => 'identidad',
						'type' => 'text',
						'instructions' => __('Nombre completo.', 'incognitos'),
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5b3b284a9162b',
									'operator' => '==',
									'value' => 'true',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5b3b280791627',
						'label' => __('ID', 'incognitos'),
						'name' => 'id',
						'type' => 'text',
						'instructions' => __('Identificador. Por ejemplo el NIF o el NIE o el CIF o etc.', 'incognitos'),
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5b3b284a9162b',
									'operator' => '==',
									'value' => 'true',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5b3b280791628',
						'label' => __('Dirección postal', 'incognitos'),
						'name' => 'direccion',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5b3b284a9162b',
									'operator' => '==',
									'value' => 'true',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5b3b280791629',
						'label' => __('Teléfono', 'incognitos'),
						'name' => 'telefono',
						'type' => 'number',
						'instructions' => __('Utilice el <a target="_blank" rel="nofollow noopener noreferrer" href="https://es.wikipedia.org/wiki/Anexo:Prefijos_telef%C3%B3nicos_mundiales">prefijo telefónico</a> (+).', 'incognitos'),
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5b3b284a9162b',
									'operator' => '==',
									'value' => 'true',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '+',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5b3b28079162a',
						'label' => __('Correo electrónico', 'incognitos'),
						'name' => 'email',
						'type' => 'email',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5b3b284a9162b',
									'operator' => '==',
									'value' => 'true',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
				),
			),
			array(
				'key' => 'field_5b3b2e3bb1f83',
				'label' => __('Datos de contacto del Delegado de Protección de Datos', 'incognitos'),
				'name' => 'responsableDpd',
				'type' => 'group',
				'instructions' => __('Persona/Empresa responsable de informar, asesorar, supervisar y cooperar con la autoridad de control, así como ser el punto de contacto para los/las interesados/das.', 'incognitos'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'row',
				'sub_fields' => array(
					array(
						'key' => 'field_5b3b2f32b1f90',
						'label' => __('El responsable hace el papel del DPD?', 'incognitos'),
						'name' => 'dpd',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'true' => __('Sí', 'incognitos'),
							'false' => __('No', 'incognitos'),
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'save_other_choice' => 0,
						'default_value' => 'true',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_5b3b2e3bb1f84',
						'label' => __('Identidad', 'incognitos'),
						'name' => 'identidad',
						'type' => 'text',
						'instructions' => __('Nombre completo.', 'incognitos'),
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5b3b2f32b1f90',
									'operator' => '==',
									'value' => 'false',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5b3b4065fb1ac',
						'label' => __('Dirección postal', 'incognitos'),
						'name' => 'direccion',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5b3b2f32b1f90',
									'operator' => '==',
									'value' => 'false',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5b3b2e3bb1f88',
						'label' => __('Correo electrónico', 'incognitos'),
						'name' => 'email',
						'type' => 'email',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5b3b2f32b1f90',
									'operator' => '==',
									'value' => 'false',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
				),
			),
			array(
				'key' => 'field_5b3b21ec3f0e7',
				'label' => __('Finalidad', 'incognitos'),
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5b3b3bc87d21c',
				'label' => __('Importante', 'incognitos'),
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => __('El <em>Reglamento General de Protección de Datos</em> aclara que la información proporcionada debe utilizar un lenguaje claro, conciso y comprensible, evitándose el abuso de citas legales, "jerga" confusa, o términos ambiguos con escaso sentido para las personas destinatarias.', 'incognitos'),
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_5b3b9fa40d188',
				'label' => __('Listado', 'incognitos'),
				'name' => 'finalidadListado',
				'type' => 'repeater',
				'instructions' => __('Los datos serán recogidos exclusivamente para fines determinados, explícitos y legítimos, y no serán tratados ulteriormente de manera incompatible con dichos fines.
	<hr>
	<strong>Constará de</strong>:
	<ol>
	<li>Descripción de los fines del tratamiento.</li>
	<li>Plazos o criterios de conservación de los datos.</li>
	<li>Decisiones automatizadas, perfiles y lógica aplicada.</li>
	</ol>', 'incognitos'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_5b3ba0270d189',
				'min' => 0,
				'max' => 0,
				'layout' => 'block',
				'button_label' => __('Añadir Finalidad', 'incognitos'),
				'sub_fields' => array(
					array(
						'key' => 'field_5b3ba0270d189',
						'label' => __('Título', 'incognitos'),
						'name' => 'titulo',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5b3ba03f0d18a',
						'label' => __('Descripción', 'incognitos'),
						'name' => 'descripcion',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 0,
						'delay' => 0,
					),
				),
			),
			array(
				'key' => 'field_5b3b21f43f0e8',
				'label' => __('Legitimación', 'incognitos'),
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5b3b417758aa4',
				'label' => __('Importante', 'incognitos'),
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => __('El <em>Reglamento General de Protección de Datos</em> aclara que la información proporcionada debe utilizar un lenguaje claro, conciso y comprensible, evitándose el abuso de citas legales, "jerga" confusa, o términos ambiguos con escaso sentido para las personas destinatarias.', 'incognitos'),
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_5b3ce8c8a2ab5',
				'label' => __('Listado', 'incognitos'),
				'name' => 'legitimacionListado',
				'type' => 'repeater',
				'instructions' => __('Base jurídica en la cual se basa el tratamiento de los datos.', 'incognitos'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_5b3ceac0a2ab8',
				'min' => 0,
				'max' => 5,
				'layout' => 'block',
				'button_label' => __('Añadir Tipo Legitimación', 'incognitos'),
				'sub_fields' => array(
					array(
						'key' => 'field_5b3ceac0a2ab8',
						'label' => __('Legitimación por', 'incognitos'),
						'name' => 'legitimacionTipo',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'consentimiento' => __('consentimiento del interesado', 'incognitos'),
							'contrato' => __('ejecución de un contrato', 'incognitos'),
							'interes' => __('Interés legítimo del Responsable, o de un tercero', 'incognitos'),
							'legal' => __('cumplimiento de una obligación legal', 'incognitos'),
							'publico' => __('misión en Interés público o ejercicio de Poderes Públicos', 'incognitos'),
						),
						'default_value' => array(
						),
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 1,
						'ajax' => 0,
						'return_format' => 'value',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b3cec7e1f0c7',
						'label' => __('Legitimación', 'incognitos'),
						'name' => 'legitimacion',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'collapsed' => 'field_5b3cecf51f0c8',
						'min' => 0,
						'max' => 0,
						'layout' => 'row',
						'button_label' => __('Añadir Legitimación', 'incognitos'),
						'sub_fields' => array(
							array(
								'key' => 'field_5b3cecf51f0c8',
								'label' => __('Título', 'incognitos'),
								'name' => 'titulo',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5b3cec19fc064',
								'label' => __('Descripción', 'incognitos'),
								'name' => 'descripcion',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 0,
								'delay' => 0,
							),
						),
					),
				),
			),
			array(
				'key' => 'field_5b3b22033f0e9',
				'label' => __('Destinatarios', 'incognitos'),
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5b3b418158aa5',
				'label' => __('Importante', 'incognitos'),
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => __('El <em>Reglamento General de Protección de Datos</em> aclara que la información proporcionada debe utilizar un lenguaje claro, conciso y comprensible, evitándose el abuso de citas legales, "jerga" confusa, o términos ambiguos con escaso sentido para las personas destinatarias.', 'incognitos'),
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_5b3cef1ab8d46',
				'label' => __('Listado', 'incognitos'),
				'name' => 'destinatariosListado',
				'type' => 'repeater',
				'instructions' => __('Cuando se haya previsto ceder o comunicar, legítimamente, los datos personales que se recogen, se informará acerca de la identidad de los destinatarios.
	<hr>
	<strong>Los destinatarios pueden ser</strong>:
	<ol>
	<li>Empresas a las cuales se les contrate un servicio de alojamiento web, bases de datos, etc.</li>
	<li>Empresas a las cuales se les contrate un servicio de análisis web, publicidad, etc.</li>
	<li>Cualquier empresa a la que se le contrate un servicio a través del cual, sea de forma digital o física, se le proporcionen los datos de los usuarios.</li>
	</ol>', 'incognitos'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_5b3cef1ab8d47',
				'min' => 0,
				'max' => 0,
				'layout' => 'block',
				'button_label' => __('Añadir Destinatario', 'incognitos'),
				'sub_fields' => array(
					array(
						'key' => 'field_5b3cef1ab8d47',
						'label' => __('Nombre', 'incognitos'),
						'name' => 'nombre',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5b3cef7ab8d49',
						'label' => __('URL del sitio web del/la destinatario/ria', 'incognitos'),
						'name' => 'url',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'https://',
					),
					array(
						'key' => 'field_5b3cef1ab8d48',
						'label' => __('Descripción', 'incognitos'),
						'name' => 'descripcion',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 0,
						'delay' => 0,
					),
				),
			),
			array(
				'key' => 'field_5b3b22103f0ea',
				'label' => __('Derechos', 'incognitos'),
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5b3b418c58aa6',
				'label' => __('Importante', 'incognitos'),
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => __('El <em>Reglamento General de Protección de Datos</em> aclara que la información proporcionada debe utilizar un lenguaje claro, conciso y comprensible, evitándose el abuso de citas legales, "jerga" confusa, o términos ambiguos con escaso sentido para las personas destinatarias.', 'incognitos'),
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_5b3cf6658f9e9',
				'label' => __('Listado', 'incognitos'),
				'name' => 'derechosListado',
				'type' => 'repeater',
				'instructions' => __('Se deberá ofrecer la información sobre los derechos que le asisten a las personas interesadas, en relación con el Responsable, de acuerdo con el RGPD.', 'incognitos'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_5b3cf6658f9ea',
				'min' => 0,
				'max' => 5,
				'layout' => 'block',
				'button_label' => __('Añadir Derecho', 'incognitos'),
				'sub_fields' => array(
					array(
						'key' => 'field_5b3cf6658f9ea',
						'label' => __('Derecho a', 'incognitos'),
						'name' => 'derecho',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'acceso' => __('solicitar el acceso a los datos personales relativos al interesado', 'incognitos'),
							'rectificacion' => __('solicitar su rectificación o supresión', 'incognitos'),
							'limitacion' => __('solicitar la limitación de su tratamiento', 'incognitos'),
							'oposicion' => __('oponerse al tratamiento', 'incognitos'),
							'portabilidad' => __('la portabilidad de los datos', 'incognitos'),
						),
						'default_value' => array(
						),
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 1,
						'ajax' => 0,
						'return_format' => 'value',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b3cf6658f9ed',
						'label' => __('Descripción', 'incognitos'),
						'name' => 'descripcion',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 0,
						'delay' => 0,
					),
				),
			),
			array(
				'key' => 'field_5b3cfa3c79b3f',
				'label' => __('Procedencia', 'incognitos'),
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5b3cfa4c79b40',
				'label' => __('Importante', 'incognitos'),
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => __('El <em>Reglamento General de Protección de Datos</em> aclara que la información proporcionada debe utilizar un lenguaje claro, conciso y comprensible, evitándose el abuso de citas legales, "jerga" confusa, o términos ambiguos con escaso sentido para las personas destinatarias.', 'incognitos'),
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_5b3cfa6d79b41',
				'label' => __('Descripción', 'incognitos'),
				'name' => 'procedenciaDescripcion',
				'type' => 'wysiwyg',
				'instructions' => __('La procedencia de los datos únicamente habrá de incluirse en el supuesto de que los datos personales no se hayan obtenido del interesado, por proceder de alguna cesión legítima, o de fuentes de acceso público.
	<hr>
	<strong>Los medios desde los que se hayan obtenido los datos pueden ser</strong>:
	<ol>
	<li>Correo postal.</li>
	<li>Correo electrónico.</li>
	<li>Mensajería instantánea.</li>
	<li>Entre otros.</li>
	</ol>', 'incognitos'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 0,
				'delay' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-rgpd',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));
	
	endif;